### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by year221** [year221/cardgametable#1]
- [x] Set up a drag and drop example with a high light zone
- [x] Server with 2 player drag and drop
- [x] drag and drop muttiple cards
- [x] flip cards
- [x] configurable layout
- [x] new game enter screen
- [x] trash card
- [x] sort card
- [x] count cards
- [x] player name
